// ------------ Services requests ------------

// POST Method
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Aniversário do Carlos",
    "description": "Aniversário do Carlos dia 22/09 na chacará tudo nosso nada deles.",
    "price": 1500,
    "image": "imagemurlaqui"
}


###
// GET method
GET http://localhost:3000/api/services

###
// GET register by ID
GET http://localhost:3000/api/service/64de1c1970e6da1d7976a197

###
// Delete method
DELETE http://localhost:3000/api/service/64de1c1970e6da1d7976a197

###
// PUT Method
PUT http://localhost:3000/api/service/64de23ff47c2e5d3e9c10ce3
Content-Type: application/json

{
    "name": "Aniversário do Pedrinho",
    "description": "Aniversário do Pedrinho dia 25/09 na chacará tudo nosso nada deles.",
    "price": 2000,
    "image": "imagemurlaqui"
}

###
// ------------ Parties requests ------------

// POST method
POST http://localhost:4000/api/parties
Content-Type: application/json

{
    "title": "Meu evento 3",
    "author": "Carlos",
    "description": "Um frevo cabuloso",
    "budget": 9000,
    "image": "imagemurl",
    "services": [
        {
            "name": "Serviços 01",
            "description": "Serviços 01 dia 22/09 na chacará tudo nosso nada deles.",
            "price": 1500,
            "image": "imagemurlaqui"
        },
        {
            "name": "Serviços 02",
            "description": "Serviços 02 dia 22/09 na chacará tudo nosso nada deles.",
            "price": 2000,
            "image": "imagemurlaqui"
        }
    ]
}

###
// GET method
GET http://localhost:4000/api/parties

###
// GET method by ID
GET http://localhost:3000/api/party/64df62f1df3f02e4c47419b5

###
// DELETE method by ID
DELETE http://localhost:3000/api/party/64de3de1b483083a130b0656

###
// UPDATE method by ID
PUT http://localhost:3000/api/party/64df62f1df3f02e4c47419b5

Content-Type: application/json

{
    "title": "Meu evento 4",
    "author": "Carlos",
    "description": "Um frevo cabuloso",
    "budget": 1000,
    "image": "imagemurl",
    "services": [
        {
            "name": "Serviços 03",
            "description": "Serviços 03 dia 25/09 na chacará tudo nosso nada deles.",
            "price": 1500,
            "image": "imagemurlaqui"
        },
        {
            "name": "Serviços 05",
            "description": "Serviços 05 dia 30/09 na chacará tudo nosso nada deles.",
            "price": 2000,
            "image": "imagemurlaqui"
        }
    ]
}
